# 异常Exception

```java
java具备健壮性:
   1. 内存   堆内存/方法区  GC 回收无用的对象。 
   2. 异常处理机制。一段程序里面出现异常 不影响其它程序的正常执行。 如果不处理 当前线程结束。     
```



```java
在程序执行期间  代码编写期间  出现很多不正常的现象。 
    1. 错误
    2. 异常
```



## 1. 错误 vs 异常

> 都是Throwable的子类。

```java
错误: Error  所有错误的父类。  不能处理。
    错误一般都是与JVM有关。 内存  硬件  无法解决的  只能程序终止。
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space  内存溢出
	at com.javasm.exception_1.ErrorDemo.main(ErrorDemo.java:16) 
    
Exception in thread "main" java.lang.StackOverflowError 栈内存溢出问题。 
```



```java
异常:
  可以处理。
 //程序运行期间: 运行时异常
//NullPointerException
//ArrayIndexOutOfBoundsException  
//ClassCastException
//ArithmeticException
//InputMismatchException
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at com.javasm.exception_1.ErrorDemo.main(ErrorDemo.java:27)    
//编译时异常
//ParseException 
```



## 2. Throwable

```java
Throwable(String message)  具体异常信息串
Throwable(String message, Throwable cause)/Throwable(Throwable cause)   异常信息传递     
```



```java
1. Throwable getCause()  获得真正原因。
2. String getMessage()    
3. void printStackTrace()  将异常或者错误信息打印输出到控制台上 (处理异常)    
```





## 3. Exception

![1616816047468](pic\1616816047468.png)

### 1. 运行时异常

> 在开发中  常遇见的一般都是运行时异常。 往往是程序员自身的问题的导致的   ==不推荐处理运行时异常==。

> 提前预判   对用户数据良好的校验。



### 2.编译时异常

> 必须要处理的。 程序无法编译。 一直报错。



## ==3. 处理异常==

### ==1. 捕获异常==

> 真正处理异常的方式

```java
try{
    //有可能会出现异常的代码 
}catch(异常类 异常对象){//捕获具体的异常类
    //处理异常对象
    //逻辑:
    //1.sout
    //2.void printStackTrace()
    //3.return 数据;
    //4.与日志框架结合。 将异常log存储到不同级别的日志文件中。Log4j (后面)
    //5.异常信息的传递--->Caused by: 真正引起问题的异常是什么。 throw
    // 低级别异常对象 传递到高级别异常对象中
}[finally{
    //释放物理资源  获得数据库连接  网络连接  打开磁盘文件   close
}]
```

```java
//多线程
try{
    //上锁
    
}finally{
    //解锁
}
```



> 处理方式1

```java
public static void main(String[] args) {

        int[] array = {1, 2, 3};

        try {
            //获得最后一个元素数据
            System.out.println(array[array.length]);//当前线程结束了
        } catch (ArrayIndexOutOfBoundsException e) {
            //System.out.println("数组索引越界了。。。");
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
        //遍历数组所有元素
        for (int i : array) {
            System.out.println("元素:" + i);
        }
    }
```



> 处理方式2

```java
 public static void main(String[] args) {

        int[] array = {1, 2, 3};

        try {
            System.out.println(3 / 0);//算术

            //异常之后的代码就不执行了
            System.out.println(array[array.length]);//越界

        } catch (ArithmeticException e) {
            System.out.println("除数不能为0");
        } catch (ArrayIndexOutOfBoundsException e) {//Exception e 多态
            e.printStackTrace();
        }

        //有多个catch块  有且只运行一个
        //区分稳定代码和非稳定的代码  禁止把所有的程序都放到try里面
        //遍历数组所有元素
        for (int i : array) {
            System.out.println("元素:" + i);
        }

    }
```

```java
 public static void main(String[] args) {

        int[] array = {1, 2, 3};

        try {
            System.out.println(3 / 1);//算术

            //异常之后的代码就不执行了
            System.out.println(array[array.length-1]);//越界

            String str = null;
            str.equals("abc");

            //必须是同一个级别的异常类
        } catch (ArithmeticException | ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
        }
     //.....
 }
```



> 模拟 : 任意2个数字执行除法运算
>
> 正常开发中对运行时异常的处理方式:

```java
 public static int divide(int num1, int num2) {
        if (num2 == 0) {
            throw (new ArithmeticException("除数不能为0"));
        }
        return num1 / num2;
    }


    public static void main(String[] args) {

        Scanner input = new Scanner(System.in);

        System.out.println("录入第一个数字:");
        int num1 = input.nextInt();
        System.out.println("录入第2个数字:");
        int num2 = input.nextInt();
        try {
            System.out.println(divide(num1, num2));
        } finally {
            input.close();
            //释放物理资源
        }
    }
```



> 计算租金： 使用捕获处理编译时异常。

```java
 private static final String PATTERN = "yyyy-MM-dd HH:mm:ss";

    public static int getMoney(String borrowTime, String backTime) {

//        Objects.requireNonNull(borrowTime,"时间数据不能为null");
//        Objects.requireNonNull(backTime,"时间数据不能为null");
        if (borrowTime == null || backTime == null) {
            throw new NullPointerException("时间数据不能为null");
        }

        //2个时间的间隔  转换成小时进行算钱  数值型的数据可以进行算术运算
        //将2个字符串的时间  ---> 先转  Date数据     转换成 ---->  数值型的数据  byte short int long  float double char
        //SimpleDateFormat  格式化时间工具类: 满足字符串与Date之间相互转换

        SimpleDateFormat dateFormat = new SimpleDateFormat(PATTERN);

        //编译时异常: 必须要处理
        Date borrowDate = null;
        Date backDate = null;
        try {
            borrowDate = dateFormat.parse(borrowTime);//将字符串解析成Date对象
            backDate = dateFormat.parse(backTime);
        } catch (ParseException e) {
            e.printStackTrace();
            System.out.println("字符串时间格式数据 与 pattern格式规定的内容  不符");
        }

        long borrow = borrowDate.getTime();//获得当前日期的毫秒数
        long back = backDate.getTime();//获得当前日期的毫秒数

        return (int) ((back - borrow) / 1000 / 3600);
    }

```



```java
java.text.ParseException: Unparseable date: "2021-03-27 12:00"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.javasm.exception_1.ExceptionDemo4.getMoney(ExceptionDemo4.java:38)
	at com.javasm.exception_1.ExceptionDemo4.main(ExceptionDemo4.java:53)
字符串时间格式数据 与 pattern格式规定的内容  不符
Disconnected from the target VM, address: '127.0.0.1:58948', transport: 'socket'
Exception in thread "main" java.lang.NullPointerException
	at com.javasm.exception_1.ExceptionDemo4.getMoney(ExceptionDemo4.java:45)
	at com.javasm.exception_1.ExceptionDemo4.main(ExceptionDemo4.java:53)
```





### 2. 抛出异常  throws

> 消极处理。 把异常抛出给上级  抛出给调用者。 (没有能力处理异常的)

> 使用throws处理运行时异常 没有任何意义。==一般都是处理编译时异常==。

```java
public void a() throws A,B,C{
    //谁调用a方法  就把A B C抛给谁
}
```



> 使用throws处理编译时异常。







## 4. throw

> 1. 控制程序。遇见throw程序停止。

```java
在方法体里面:
   throw (new 异常类构造);
```

```java
if (num2 == 0) {
    throw (new ArithmeticException("除数不能为0"));
 }

//----------------------------------------
if (obj == null)
      throw new NullPointerException();
```



> 2. 异常信息传递

```java
将低级别异常对象传递到高级别的异常对象中，这样会帮助我们快速定位产生异常的真正原因。
//编译时异常: 必须要处理
Date borrowDate = null;
Date backDate = null;
try {
    borrowDate = dateFormat.parse(borrowTime);//将字符串解析成Date对象
    backDate = dateFormat.parse(backTime);
} catch (ParseException e) {
   //异常信息传递: 
    try {
        throw new Exception(e);
    } catch (Exception e1) {
        e1.printStackTrace();
    }
}    
```

```java
java.lang.Exception: java.text.ParseException: Unparseable date: "2021-03-27 12:00"
	at com.javasm.exception_1.ExceptionDemo4.getMoney(ExceptionDemo4.java:44)
	at com.javasm.exception_1.ExceptionDemo4.main(ExceptionDemo4.java:58)
Caused by: java.text.ParseException: Unparseable date: "2021-03-27 12:00"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.javasm.exception_1.ExceptionDemo4.getMoney(ExceptionDemo4.java:38)
	... 1 more
Disconnected from the target VM, address: '127.0.0.1:58977', transport: 'socket'
Exception in thread "main" java.lang.NullPointerException
	at com.javasm.exception_1.ExceptionDemo4.getMoney(ExceptionDemo4.java:50)
	at com.javasm.exception_1.ExceptionDemo4.main(ExceptionDemo4.java:58)
```



> 3. throw 与自定义异常结合使用

```java
public class UserPay {

    private static int balance = 2000;//余额

    /**
     * 支付的总钱数
     *
     * @param money
     */
    public static void pay(int money) throws BalanceException{

        if (money > balance) {
            throw new BalanceException("用户余额不足，无法支付",10001);
        }
        balance -= money;
    }

    public static void main(String[] args) {

        int money = 3000;
        System.out.println("需要支付:" + money);
        try {
            pay(money);
        } catch (BalanceException e) {

            e.printStackTrace();
            System.out.println(e.getCode());
            System.out.println(e.getMessage());
        }

    }
}
```



## 5. 自定义异常类

> 模拟： 用户支付。  jdk提供很多 异常类 不符合业务需求。





